### PR TITLE
Dedicated link creation dialog

### PR DESCRIPTION
**Pull request by mberry**
Added save button which opens link creation form
Will also open on ctrl+v and paste the url
Only shows url field at first, then autofills with title
Has a 1500ms debounce to keep it from opening prematurely if the user 
is typing the address.
Closes dialog form after link created

### CODE REVIEW

**Comment by kirillt** [comment]
Is it correct to imagine that the "AUTO FILLED" button is invisible now and it automatically pressed every 1.5s?

**Comment by mberry** [comment]
It sets a timer the moment a key is pressed, if the key is pressed again it resets. If the timer hits zero it makes the network connection to autofill.

**Comment by kirillt** [comment]
@mberry we need update this PR to catch up with `main`. By the way, let's target `main` in all PRs for the time being.

**Comment by mberry** [comment]
Replaced by #47

**Pull request closed without merging**
